version: '3.9'
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    command: ['./wait-for-it.sh', 'db:${POSTGRES_PORT}', '--', 'python3', 'main.py']
    depends_on:
      - db
    environment:
      - CONFIG_FILE_PATH
      - SLACK_APP_TOKEN
      - SLACK_BOT_TOKEN
      - SLACK_USER_TOKEN
      - POSTGRES_HOST
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_PORT
      - FLASK_APP_SECRET_KEY
      - DEFAULT_WEB_ADMIN_PASSWORD
      - JWT_SECRET_KEY
      - FLASK_DEBUG_MODE_ENABLED
      - GITHUB_API_KEY
      - GITHUB_REPO
      - GITHUB_ISSUE_TEMPLATE_PATH
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
        mode: host
    links:
      - db
    volumes:
      # Wherever the config file lives, root by default
      - ./backend/config.yaml:/config/incident-bot/config.yaml
  db:
    image: postgres:13
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
    command:
      ['postgres', '-c', 'log_statement=all', '-c', 'log_destination=stderr']
    hostname: ${POSTGRES_HOST}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
